env:
  TERM: xterm-256color
font:
  size: 18
  normal:
    family: Meslo LGLDZ Nerd Font Mono
    style: Regular
  bold:
    family: Meslo LGLDZ Nerd Font Mono
    style: Regular
  italic:
    family: Meslo LGLDZ Nerd Font Mono
    style: Regular
  bold_italic:
    family: Meslo LGLDZ Nerd Font Mono
    style: Regular
window:
  opacity: 0.8
  dynamic_padding: true
